Calendar Domain 작성
What-s-Your-Plan/wypl-backend pull request #12
Opened 2024-09-14 02:04 UTC by sjhjack

## 📑 개요

- #3 

### ✅ PR 체크리스트

---

- [X] 🔀 PR 제목의 형식을 잘 작성했나요?
- [ ] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 빌드는 성공했나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

### 🚀 상세 작업 내용

---

모든 Entity의 `extends BaseEntity` 부분은 Todo 로 작성했습니다.

- [X] Calendar Entity 작성
- [X] MemberCalendar Entity 작성
&emsp;- 복합키를 위한 MemberCalendarId 작성
&emsp;- InviteStatus enum 작성
- [X] Schedule Entity 작성
- [X] ScheduleInfo Entity 작성
- [X] Repetition Entity 작성
&emsp;- RepetitionCycle enum 작성

### 📁 ETC

---

2024-09-14 11:47 UTC, jiwon83 reviewed
몇가지 논의 사항이 있어서 답글 부탁 드립니다!

2024-09-14 11:47 UTC, jiwon83 commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/calendar/domain/MemberCalendarId.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
Protected로 접근 제한 설정한 거 좋은 전략인 것 같아요! LGTM!

2024-09-14 13:16 UTC, KIMSEI1124 requested changes
전체적으로 좋습니다!

회의를 진행하면서 정해야할 것이 있을 것 같은데, 컬럼명을 명시적으로 다 적어주는게 좋을지 궁금하여 이것은 내일 진행해보도록 하겠습니다!

2024-09-15 05:25 UTC, sjhjack commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/calendar/domain/Calendar.java
> +    @Column(name = "calendar_id")
`_` 가 들어가서 적어놨어요!

2024-09-15 05:38 UTC, sjhjack commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/schedule/domain/Schedule.java
> +    private String description;
name 속성 추가하겠습니다!
title은 처음에 제약이 없어서 안 적어뒀고, description은 length의 default 값이 255라서 명시하지 않았습니다!
title은 length 추가하도록 할게요.

2024-09-15 06:00 UTC, jiwon83 commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/calendar/domain/MemberCalendar.java
> +@SQLRestriction("deleted_at is null")
이후에, 실행취소 기능을 위해서 soft delete로 할게요!

2024-09-15 06:17 UTC, sjhjack commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/schedule/domain/Repetition.java
> +//    private Object dateOfYear;      // 논의 필요
enum으로 관리하고, 컬럼은 삭제했습니다.

2024-09-15 06:18 UTC, KIMSEI1124 commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/schedule/domain/ScheduleInfo.java
> +
논의를 해봐야할 것 같지만, 그룹에 있는 모든 인원들이 수정을 해야한다고 생각하지만 이 상황이라면 마지막에 수정한 사람이 누구인지 모를 것 같습니다!...

추후 논의 할 수 있도록 다른 곳에 올려둘게요!

2024-09-15 06:18 UTC, KIMSEI1124 approved these changes
LGTM!

2024-09-15 06:41 UTC, merged