일정 생성 API 작성
What-s-Your-Plan/wypl-backend pull request #35
Opened 2024-10-02 04:26 UTC by jiwon83

## 📑 개요
- #26  

### ✅ PR 체크리스트

---

- [x] 🔀 PR 제목의 형식을 잘 작성했나요?
- [ ] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?

### 🚀 상세 작업 내용

---

- 할일 생성 서비스, 컨트롤러 작성
- 공통 Message 파일 추가, 관련 com.fasterxml.jackson.core:jackson-annotations:2.15.2 라이브러리 의존성 추가

### 📁 ETC

---
closes #26

2024-10-02 10:25 UTC, KIMSEI1124 requested changes
@jiwon83 

해당 PR을 열심히 진행해주셔서 감사합니다! 👍🏼 
코드를 보면서 궁금한 점과 수정해야할 점에 대해서 자세히 작성해두었습니다.

보시면서 궁금한 점이나 다양한 의견을 남기고 싶으면 코멘트를 달아주세요! 😄

2024-10-02 10:25 UTC, KIMSEI1124 commented on application/wypl-core/src/main/java/com/wypl/wyplcore/schedule/controller/ScheduleController.java
> +    }
`ResponseEntity`가 아닌 [WyplResponseEntity](https://github.com/What-s-Your-Plan/wypl-backend/blob/2eddec2/application/application-common/src/main/java/com/wypl/applicationcommon/WyplResponseEntity.java)를 사용해보는게 어떨까요?

```java
    @PostMapping
    public WyplResponseEntity<ScheduleInfoCreateResponse> addSchedule(@Authenticated AuthMember authMember, @RequestBody ScheduleCreateRequest scheduleCreateRequest) {
        ScheduleInfoCreateResponse response = scheduleService.createSchedule(authMember.id(), scheduleCreateRequest)
        return WyplResponseEntity.created(response, "일정 생성 성공");
    }
```

로 처리할 수 있을 것 같아요!

2024-10-02 10:25 UTC, KIMSEI1124 commented on common/build.gradle
>  }
`Common` 모듈은 아무런 종속성도 가지고 있으면 안됩니다!...

![2024-10-02_19-21-49](https://github.com/user-attachments/assets/d2613d53-c276-4f1b-b494-1c7c59845d0b)

저희 컨벤션은 우아한 멀티 모듈의 블로그 글을 따라서 하고 있는데 외부 의존 관계를 갖고 있으면 안됩니다!..

2024-10-02 10:25 UTC, KIMSEI1124 commented on common/src/main/java/com/wypl/common/Message.java
해당 내용은 위에서 코멘트한 `WyplResponseEntity`로 처리할 수 있으니 없애도 괜찮지 않을까요?!

2024-10-02 10:25 UTC, KIMSEI1124 commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/calendar/mapper/ScheduleInfoMapper.java
>      }
혹시 중간에 매개변수를 수정하신 이유가 있을까요?

인터페이스로 한다면 클래스의 수는 많아지겠지만, 서로에 대한 간섭이 줄어들 수 있다는 장점이 있는데 어떠한 점때문에 수정하신지 궁금합니다!

2024-10-06 05:58 UTC, jiwon83 commented on domain/jpa-calendar-domain/src/main/java/com/wypl/jpacalendardomain/calendar/mapper/ScheduleInfoMapper.java
>      }
scheduleInfo 엔티티를 생성하는 데 필요한 필드가 creatorId 1개뿐이어서 수정했었습니다! 
scheduleInfo에 필드가 추가되면 관련 코드를 변경해야하는 문제가 있을 수 있기는 합니다. 해당 부분 논의해 보면 좋을 것 같습니다 : )

2024-10-06 07:33 UTC, KIMSEI1124 approved these changes
LGTM!

2024-10-06 07:38 UTC, merged