Open Weather API를 연동
What-s-Your-Plan/wypl-backend pull request #37
Opened 2024-10-06 07:12 UTC by KIMSEI1124

## 📑 개요

- #31 

### ✅ PR 체크리스트

---

- [X] 🔀 PR 제목의 형식을 잘 작성했나요?
- [X] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 빌드는 성공했나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

### 🚀 상세 작업 내용

---

- [X] Openweather Client 코드 작성
- [X] 날씨 상태에 따른 분류
- [X] 날씨 조회하는 도시 목록 작성

### 📁 ETC

---

2024-10-11 01:43 UTC, sjhjack requested changes
고생하셨습니다~!!

2024-10-11 01:43 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherClient.java
> +}
Client class가 아닌 interface로 만든 이유가 있을까요?
application 단에서 인터페이스로 통신하기 위해서 인가요?
cond 사용하는 것은 저도 고민해볼게요!

2024-10-11 01:43 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherClientImpl.java
> +		}
`response.getStatusCode()` 부분을 `HttpStatus status = response.getStatusCode();`로 따로 빼는 것은 어떻게 생각하시나요?
`status.is2xxSuccessful()`이 더 보기 편한 것 같아서 의견 남겨봅니다!

2024-10-11 01:43 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherProperties.java
> +@Data
꼭 필요한게 아니라면 가급적 수정해주세요!!

2024-10-11 01:43 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/data/OpenWeatherResponse.java
> +	public static WeatherResponse ofByWeatherResponse(final int id, final String main, final String desc) {
이 메서드만 파라미터를 한 줄로 나열한 이유가 있나요?

2024-10-11 01:43 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/data/OpenWeatherResponse.java
> +	}
파라미터가 여러 개일 때는 `of` 네이밍이 더 적절한 것 같습니다!

2024-10-11 01:43 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/type/WeatherType.java
> +@Generated
`@Generated`를 사용한 이유가 궁금합니다!

2024-10-13 09:29 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/type/WeatherType.java
> +@Generated
해당 코드는 단순히 타입을 명시하기 위한 클래스 파일이여서 테스트가 필요하지 않을 것 이라고 판단하여 사용했습니다.

2024-10-13 09:51 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherProperties.java
> +@Data
해당 객체는 `ymal`에 있는 설정 값을 가져오기 때문에 반드시 `@Setter`가 필요하므로 여러개의 어노테이션을 작성하는 것 보다 `@Data`를 작성하는게 더 좋다고 생각했습니다!

만약 다른 특이한 문제사항이 있을까요?!

2024-10-13 09:52 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherClientImpl.java
> +		}
캡슐화를 진행해보겠습니다!

`response.getStatusCode().is2xxSuccessful()`를 `response..isStatusCode2xxSuccessful()`로 수정해보도록 하겠습니다!

2024-10-13 09:53 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherClient.java
> +}
추후 V2 버전으로 더 좋은 기능이 생기거나 다른 개발자가 더 좋은 기능을 개발할 수 있다고 생각하여 확장성있게 만들어뒀습니다!
추후 PSA를 위해 인터페이스로 한 이유도 있습니다!

2024-10-14 08:14 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherClientImpl.java
> +		}
해당 내용을 수정했습니다!

2024-10-14 08:16 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/data/OpenWeatherResponse.java
> +	}
수정했습니다!

2024-10-16 02:22 UTC, sjhjack commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherProperties.java
> +@Data
혹시 `@ToString`, `@EqualsAndHashCode` 도 쓰이고 있나요?
그렇지 않다면 불필요한 내용도 포함해야 할까 싶어서요!

2024-10-17 04:06 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/data/OpenWeatherResponse.java
> +	public static WeatherResponse ofByWeatherResponse(final int id, final String main, final String desc) {
수정하였습니다!

2024-10-17 04:07 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/OpenWeatherProperties.java
> +@Data
`@EqualsAndHashCode`는 불필요하다고 생각합니다!
그리고 `@ToString`과 같은 경우에는 추후 해당 클래스를 로그로 남겼을 때, 민감한 값들이 노출될 수 있다고 판단하여 수정하였습니다!

현재는 `@Setter`, `@Getter`로 변경하였습니다.

2024-10-17 04:09 UTC, KIMSEI1124 reviewed
@sjhjack 

주신 코멘트를 모두 확인하였고, 수정하였습니다!

2024-10-17 04:09 UTC, KIMSEI1124 commented on client/openweather-client/src/main/java/com/wypl/openweatherclient/config/OpenWeatherProperties.java
> +}
@sjhjack 

해당 부분을 수정하였습니다!

2024-10-17 05:10 UTC, sjhjack approved these changes
고생하셨습니다!!

2024-10-17 05:15 UTC, merged