Google OAuth2 Token API 연동
What-s-Your-Plan/wypl-backend pull request #40
Opened 2024-10-20 11:57 UTC by sjhjack

## 📑 개요

- #33 

### ✅ PR 체크리스트

---

- [X] 🔀 PR 제목의 형식을 잘 작성했나요?
- [ ] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 빌드는 성공했나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

### 🚀 상세 작업 내용

---

- [X] Google OAuth2 Access Token, Refresh Token 발급 요청 
- [X] Google OAuth2 Access Token 재발급 요청
- [X] `GoogleOAuthParamFactory` 팩토리 클래스 및 메서드 체이닝 적용
- [X] 토큰 요청 관련 예외 처리

### 📁 ETC

---

colsed: https://github.com/What-s-Your-Plan/wypl-backend/issues/33

2024-10-20 12:04 UTC, KIMSEI1124 requested changes
리뷰를 달아뒀습니다!

수정이 필요한 부분이 있어 코멘트를 달아뒀습니다!

2024-10-20 12:04 UTC, KIMSEI1124 commented on application/wypl-core/src/test/java/com/wypl/wyplcore/GoogleOAuthTest.java
해당 파일은 삭제해주세요!

의미가 없는 테스트 코드인 것 같습니다!

2024-10-20 12:04 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/GoogleOAuthFactory.java
해당 주석인 파일은 제거해주세요!

2024-10-20 12:04 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/GoogleOAuthProperties.java
> +	// 서버말고 yml만 따로 빌드할 수 있다 -> 편의성 굿
사용하지 않는 주석은 삭제해주세요!

2024-10-20 12:04 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/data/response/GoogleTokenResponse.java
> +@Builder
Response인데 빌더가 있는 이유가 있을까요?

2024-10-20 12:04 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/exception/GoogleOAuthErrorCode.java
> +	MALFORMED(400, "GOOGLE_OAUTH_002", ""),
에러 메시지 추가 부탁드립니다!

2024-10-20 12:04 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/GoogleOAuthClient.java
> +			log.warn(e.getMessage());
해당 로그는 내부 서버 오류 위로 옴겨주세요!

알 수 없는 경우에만 로그를 작성하면 좋을 것 같습니다.

2024-10-20 12:04 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/GoogleOAuthClient.java
> +			throw new WyplException(GlobalErrorCode.INTERNAL_SERVER_ERROR);
```suggestion
			if (e.getMessage().contains("Malformed")) {
				throw new GoogleOAuthException(GoogleOAuthErrorCode.MALFORMED);
			}
			if (e.getMessage().contains("Bad Request")) {
				throw new GoogleOAuthException(GoogleOAuthErrorCode.BAD_REQUEST);
			}
			log.warn(e.getMessage());
			throw new WyplException(GlobalErrorCode.INTERNAL_SERVER_ERROR);
```

2024-10-26 02:46 UTC, sjhjack commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/data/response/GoogleTokenResponse.java
> +@Builder
Request처럼 생각하면서 추가했습니다. 일관된 응답을 받기 때문에 필요 없을 것 같습니다.
삭제했습니다!

2024-10-26 02:46 UTC, sjhjack commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/GoogleOAuthClient.java
> +			log.warn(e.getMessage());
의견 감사합니다!

2024-10-26 03:20 UTC, KIMSEI1124 approved these changes
LGMT!

전체적으로 잘 작성하셨습니다!! 다음 작업을 진행하기 전에 해당 브랜치를 머지해주시고 제가 제안하는 내용이 하나 있는데 확인해보시고 변경해야할 것 같으면 수정해주세요!

2024-10-26 03:20 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/exception/GoogleOAuthErrorCode.java
> +	MALFORMED(400, "GOOGLE_OAUTH_002", "오염된 토큰입니다."),
오염된 토큰?? 이라는 말 보다는 잘못된 토큰이라는 이라고 알려주면 좋을 것 같아요!

사용자가 봐도 이해할 수 있도록 하면 좋을 것 같습니다!

2024-10-26 03:20 UTC, KIMSEI1124 commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/exception/GoogleOAuthErrorCode.java
> +	MALFORMED(400, "GOOGLE_OAUTH_002", "오염된 토큰입니다."),
```suggestion
	MALFORMED(400, "GOOGLE_OAUTH_002", "올바르지 않은 토큰입니다."),
```

이 처럼 수정하면 괜찮지 않을까요?!

2024-11-02 13:06 UTC, jiwon83 approved these changes
고생했습니다 : )

2024-11-03 06:58 UTC, sjhjack commented on client/google-oauth-client/src/main/java/com/wypl/googleoauthclient/exception/GoogleOAuthErrorCode.java
> +	MALFORMED(400, "GOOGLE_OAUTH_002", "오염된 토큰입니다."),
좋은 의견 감사합니다!
반영했습니다.

2024-11-03 06:59 UTC, merged