로그인 로직 개발
What-s-Your-Plan/wypl-backend pull request #53
Opened 2024-12-29 12:49 UTC by sjhjack

## 📑 개요

- #41 

### ✅ PR 체크리스트

---

- [X] 🔀 PR 제목의 형식을 잘 작성했나요?
- [X] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 빌드는 성공했나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

### 🚀 상세 작업 내용

---

- [x] UserInfo 요청 Google API 추가
- [x] Birthday 요청 Google API 추가
  - 생일 비공개 유저 저장 로직 추가
- [x] GoogleOAuthClient 모듈의 public 메서드에 설명 주석 추가
- [x] AuthController, AuthService 작성
- [x] 로그인/회원가입 기능 구현
  - 로그인/회원가입 분기 처리
    - DB 조회 O : 로그인 처리 (토큰 정보 저장)
    - DB 조회 X : 회원가입 처리 (회원 정보, 토큰 정보 저장)
- [x] 토큰 재발급 기능 구현
  - 토큰 유효성 검증 분기 처리
    - Redis 조회 O : 토큰 재발급 에러 (401)
    - Redis 조회 X : 잘못된 토큰 에러 (400)
- [x] 회원 탈퇴 기능 구현
  - Redis에서 토큰 정보 삭제
  - 회원 정보 Hard Delete -> 추후 논의 후 변경 예정
- [x] Redis Token 모듈 작성
  - {key : value} = {access_token : refresh_token} 으로 저장 (refresh_token 만료기한 만큼)
  - 토큰 정보 저장, 삭제, 조회 기능 작성
- [x] 전체 테스트 코드 작성

### 📁 ETC

---

closed: #41

2024-12-31 04:36 UTC, KIMSEI1124 requested changes
해당 이슈 처리하시느라 고생하셨습니다! 👍🏼 

몇가지 궁금한 사항들을 작성해두었고 수정해야하는 목록에 대해서도 코멘트를 달아두었습니다!
하시다가 궁금하신 내용이 있다면 질문해주시면 감사합니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on application/wypl-core/src/main/java/com/wypl/wyplcore/auth/controller/AuthController.java
> +@Slf4j
사용하지 않는 기능의 어노테이션은 삭제해주시면 감사합니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on application/wypl-core/src/main/java/com/wypl/wyplcore/auth/service/AuthServiceImpl.java
> +		// FIXME : member Id를 같이 보내야할까? 안 보내도 될 것 같은데.. redis에 access_token : {refresh_token, member_id}로 저장?
음 이 내용에 대해서는 `memberId`를 전송하지 않아도 괜찮을 것 같습니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on application/wypl-core/src/test/java/com/wypl/wyplcore/auth/controller/AuthControllerTest.java
해당 테스트가 Github Actions에서 실패하는 것으로 파악됩니다! 원인을 분석해보시고 알려주세요!

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/redis-token-domain/src/test/java/com/wypl/redistokendomain/TokenRepositoryTest.java
> +			assertThat(result).isEqualTo(false);
`assertThat(result).isEqualTo(false);` 대신에 `assertThat(result).isFalse();` 가 있습니다! 해당 내용을 사용해는건 어떤가요?

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/test/java/com/wypl/jpamemberdomain/SocialMemberRepositoryTest.java
> +			assertThat(result.getOauthProvider()).isEqualTo(findSocialMember.getOauthProvider());
이렇게 하나씩 하는 것 보다 재귀적으로 확인할 수 있는 테스트 방법이 있습니다!

해당 방법으로 수정해보시고, 발생하는 문제점을 해결해보시면 좋을 것 같습니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/utils/SocialMemberRepositoryUtils.java
> +	}
해당 내용을 보아하니 구글에 종속이 되어 보입니다!

만약 다른 로그인 방식이 생긴다면 어떻게 처리하실건가요?!

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/data/MemberDto.java
해당 Dto는 어떠한 이유때문에 생성한 Dto인가요?!

이름이 모호해서 다른 Dto가 생긴다면 헷갈릴 수 있다고 생각합니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/data/SocialMemberDto.java
`MemberDto` 와 동일한 질문입니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/auth-domain/src/test/java/com/wypl/authdomain/auth/service/fixture/MemberFixture.java
> +// @AllArgsConstructor
주석 내용을 해결해주시면 감사합니다!

2024-12-31 04:36 UTC, KIMSEI1124 commented on domain/auth-domain/src/main/java/com/wypl/authdomain/auth/service/AuthDomainServiceImpl.java
```java
@Transactional(readOnly = true)
@RequiredArgsConstructor
@Service
public class AuthServiceImpl {
```

에서는 `@Transactional(readOnly = true)`를 작성하셨는데 해당 서비스에서는 안하신 이유가 있을까요?!

2025-01-01 08:45 UTC, sjhjack commented on application/wypl-core/src/main/java/com/wypl/wyplcore/auth/service/AuthServiceImpl.java
> +		// FIXME : member Id를 같이 보내야할까? 안 보내도 될 것 같은데.. redis에 access_token : {refresh_token, member_id}로 저장?
같이 고민해주셔서 감사합니다!

2025-01-01 08:47 UTC, sjhjack commented on application/wypl-core/src/test/java/com/wypl/wyplcore/auth/controller/AuthControllerTest.java
원인 알아보고 공유하겠습니다!

2025-01-01 08:48 UTC, sjhjack commented on domain/redis-token-domain/src/test/java/com/wypl/redistokendomain/TokenRepositoryTest.java
> +			assertThat(result).isEqualTo(false);
좋은 지적 감사합니다! 가독성이 향상되는 장점이 있겠네요. 반영하겠습니다.

2025-01-01 08:55 UTC, sjhjack commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/data/MemberDto.java
회원가입 로직에서 저장할 데이터를 담기 위한 Dto 입니다.
의도를 명확히 하기 위해 `MemberSaveDto` 처럼 이름을 변경하는게 낫다고 생각하시나요?

2025-01-01 08:55 UTC, sjhjack commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/data/SocialMemberDto.java
`MemberDto`와 동일합니다!

2025-01-01 08:59 UTC, sjhjack commented on domain/auth-domain/src/main/java/com/wypl/authdomain/auth/service/AuthDomainServiceImpl.java
제대로 확인하지 못한 것 같습니다!
해당 클래스를 다시 살펴보니, `saveAuthData`와 `deleteToken`에도 `@Transactional`이 누락된 것을 확인했습니다.
누락된 내용도 포함해서 수정하겠습니다.

2025-01-01 09:13 UTC, sjhjack commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/utils/SocialMemberRepositoryUtils.java
> +	}
좋은 지적 감사합니다!
현재 생각으로는 `OauthProvider`를 파라미터로 전달받도록 할 것 같습니다.
메서드를 사용하는 모든 곳에서 수정해야 한다는 번거로움이 있지만, 아직 다른 방법이 떠오르지 않습니다 😢 

혹시 고려해볼 방법이 있을까요?

2025-01-01 09:17 UTC, sjhjack commented on domain/auth-domain/src/test/java/com/wypl/authdomain/auth/service/fixture/MemberFixture.java
> +// @AllArgsConstructor
`@AllArgsConstructor`가 인식되지 않는 원인을 아직 해결하지 못해서 해당 부분 주석 처리 후 생성자를 명시적으로 추가해놓은 상태입니다.
해결하는 대로 더 고민해보겠습니다!

2025-01-01 09:30 UTC, sjhjack commented on domain/jpa-member-domain/src/test/java/com/wypl/jpamemberdomain/SocialMemberRepositoryTest.java
> +			assertThat(result.getOauthProvider()).isEqualTo(findSocialMember.getOauthProvider());
확인해보니 `isEqualTo()` 메서드는 Object끼리 비교가 가능하여 `assertThat(result).isEqualTo(findSocialMember)` 으로 수정했습니다!
의도하신 방법이 맞을까요?

2025-01-01 09:59 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/utils/SocialMemberRepositoryUtils.java
> +	}
사실 파라미터를 제외하면 생각할 방법이 메서드의 이름에다 어떤 제공자에게 인증을 받았는지 적어주는 방법이 생각납니다!

```java
public static SocialMember getSocialMemberByGoogle(SocialMemberRepository socialMemberRepository, String id) {
    return socialMemberRepository.findByOauthProviderAndOauthId(OauthProvider.GOOGLE, id)
	.orElseThrow(() -> new MemberException(MemberErrorCode.NO_SUCH_MEMBER));
}
```

하지만 새로운 제공자가 생기면 메서드가 하나씩 늘어난다는 단점이 있습니다! 한번 고민해 보시고 선택하면 좋을 것 같아요!

2025-01-01 09:59 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/main/java/com/wypl/jpamemberdomain/member/data/MemberDto.java
저는 개인적으로 클래스의 이름을 명확히 작성해주는게 더 좋다고 생각합니다! 😄

2025-01-01 10:03 UTC, KIMSEI1124 commented on domain/jpa-member-domain/src/test/java/com/wypl/jpamemberdomain/SocialMemberRepositoryTest.java
> +			assertThat(result.getOauthProvider()).isEqualTo(findSocialMember.getOauthProvider());
다른 방법을 의도하였는데! 해당 방법으로 성공이 되었군요! 아마도 `BaseEntity`를 `extends` 하지 않아서 그런 것 같습니다!

2025-01-01 11:15 UTC, KIMSEI1124 commented on .github/workflows/backend-server-test.yml
> +        run: ./gradlew test -i
음.. 해당 github actions 의 명령어를 `./gradlew clean test -i`로 해도 좋을 것 같아요!

2025-01-05 08:15 UTC, KIMSEI1124 approved these changes
전체적으로 잘 된 것 같습니다!!

해당 이슈 개발하느라 엄청 고생많으셨습니다! 👍🏼 
먼저 `Approve`를 해두었습니다! 몇몇 희망사항을 적어봤는데 한번 봐주시면 좋을 것 같습니다!

2025-01-05 08:15 UTC, KIMSEI1124 commented on application/wypl-core/src/main/java/com/wypl/wyplcore/auth/service/AuthServiceImpl.java
> +		// Todo : 회원 탈퇴 로직 논의
해당 논의가 필요하다는 내용으로 이슈를 하나 만들어주세요! 👍🏼

2025-01-05 08:15 UTC, KIMSEI1124 commented on application/wypl-core/src/test/java/com/wypl/wyplcore/auth/controller/AuthControllerTest.java
> +@WebMvcTest(AuthController.class)
Good! 따로 작성하신 문서를 봤는데 잘 해결하신 것 같아요!

그렇다면 `@ControllerTest` 와 같은 어노테이션을 만들어서 처리할 수 있을 것 같은데 따로 이슈를 만들어서 해결해보는건 어떨까요?!

2025-01-05 08:15 UTC, KIMSEI1124 commented on application/wypl-core/src/test/resources/application.yml
해결되었다면 해당 내용은 필요 없을 것 같습니다!

만약 주석으로 처리한다면 🔥 삭제하는게 좋을 것 같아요!

2025-01-05 12:16 UTC, sjhjack commented on application/wypl-core/src/main/java/com/wypl/wyplcore/auth/service/AuthServiceImpl.java
> +		// Todo : 회원 탈퇴 로직 논의
정리해서 올려보겠습니다!

2025-01-05 12:21 UTC, sjhjack commented on domain/jpa-member-domain/src/test/java/com/wypl/jpamemberdomain/SocialMemberRepositoryTest.java
> +			assertThat(result.getOauthProvider()).isEqualTo(findSocialMember.getOauthProvider());
이런 방법도 있었군요! 배워갑니다. 감사합니다 😄

2025-01-05 12:26 UTC, sjhjack commented on application/wypl-core/src/test/resources/application.yml
넵! 문제가 해결되었으니 필요 없는 부분은 모두 삭제하겠습니다.

2025-01-05 12:29 UTC, sjhjack commented on application/wypl-core/src/test/java/com/wypl/wyplcore/auth/controller/AuthControllerTest.java
> +@WebMvcTest(AuthController.class)
좋은 의견입니다!
두 어노테이션을 합해서 만들어보겠습니다.

2025-01-05 12:46 UTC, sjhjack commented on .github/workflows/backend-server-test.yml
> +        run: ./gradlew test -i
실행 속도는 느려지지만 최신 상태에서 테스트 하는 것이 더 중요해보이네요. 반영하겠습니다!

2025-01-07 10:50 UTC, merged